
name: Deploy GitHub Pages (docs)

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - "PRIVACY_POLICY.html"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure docs has latest policy
        run: |
          mkdir -p docs
          if [ -f PRIVACY_POLICY.html ]; then cp PRIVACY_POLICY.html docs/PRIVACY_POLICY.html; fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
