
name: Firebase Test Lab (Android)

on:
  workflow_dispatch:
  push:
    paths:
      - "client-android/**"
      - ".github/workflows/ftl-android.yml"

jobs:
  ftl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build APKs for testing
        working-directory: client-android
        run: |
          ./gradlew :app:assembleStoreDebug :app:assembleStoreDebugAndroidTest
          ls -l app/build/outputs/apk/store/debug/

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Run tests on Firebase Test Lab (Pixel 6, Android 14)
        run: |
          gcloud firebase test android run             --type instrumentation             --app client-android/app/build/outputs/apk/store/debug/app-store-debug.apk             --test client-android/app/build/outputs/apk/androidTest/store/debug/app-store-debug-androidTest.apk             --device model=oriole,version=34,locale=en,orientation=portrait             --timeout 5m             --results-bucket "gs://${{ secrets.GCP_RESULTS_BUCKET }}"             --results-dir "setouta/${{ github.run_id }}"

      - name: Upload FTL logs (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ftl-results-info
          path: |
            **/results/*/*.xml
            **/results/*/*.txt
        continue-on-error: true
