
name: Server CI (Docker + Tests)

on:
  push:
    paths:
      - "server-fastapi/**"
      - ".github/workflows/server-ci.yml"
  pull_request:
    paths:
      - "server-fastapi/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        working-directory: server-fastapi
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        working-directory: server-fastapi
        run: pytest -q

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t setouta/server:ci -f server-fastapi/Dockerfile .
      - name: Run container & check /health
        run: |
          docker run -d --rm -p 8000:8000 --name setouta-ci setouta/server:ci
          for i in {1..20}; do
            sleep 1
            if curl -sf http://localhost:8000/health >/dev/null; then echo "Server up"; break; fi
          done
          curl -s http://localhost:8000/health | tee /tmp/health.json
          docker logs setouta-ci | tail -n 50
          docker stop setouta-ci

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: docker
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/setouta-server:latest
          docker build -t $IMAGE -f server-fastapi/Dockerfile .
          docker push $IMAGE
